<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>naikeri-signaling-gateway</artifactId>
        <groupId>com.naikeri</groupId>
        <version>1.00.001</version>
    </parent>

    <name>naikeri-signaling-gateway :: http-diameter-gw</name>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.telzar</groupId>
    <artifactId>naikeri-diameter-gateway</artifactId>
    <version>1.00.001</version>

    <properties>
        <jdiameter.version>1.7.1-157</jdiameter.version>
        <!--paho.version>1.2.0</paho.version-->
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.naikeri</groupId>
            <artifactId>naikeri-signaling-gateway-core</artifactId>
            <version>1.00.001</version>
        </dependency>

        <dependency>
            <groupId>org.mobicents.diameter</groupId>
            <artifactId>jdiameter-api</artifactId>
            <version>${jdiameter.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mobicents.diameter</groupId>
            <artifactId>jdiameter-impl</artifactId>
            <version>${jdiameter.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mobicents.diameter</groupId>
            <artifactId>restcomm-diameter-mux-jar</artifactId>
            <version>${jdiameter.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/libs
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>libs/</classpathPrefix>
                            <mainClass>com.telzar.HttpDiameterGateway</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <!--plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>com.telzar.HttpDiameterGateway</mainClass>
                                </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin-->
        </plugins>
    </build>

</project>