<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>naikeri-signaling-gateway</artifactId>
        <groupId>com.naikeri</groupId>
        <version>1.01.002</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.partner</groupId>
    <artifactId>home-re-routing</artifactId> 
    <version>1.02.002</version>
    
    <dependencies>
        <dependency>
            <groupId>com.naikeri</groupId>
            <artifactId>core</artifactId>
            <version>1.02.002</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Build an executable JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>com.partner.hrr.impl.HomeReRouting</mainClass>
                        </manifest>
                    </archive>
                    <excludes>
                        <exclude>log4j.xml</exclude>
                        <exclude>naikeri-signaling-gateway.xml</exclude>
                        <exclude>map-application-rules.xml</exclude>
                        <exclude>map-configuration-layers.xml</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>